services:
  database:
    container_name: tzomet-sfarim-shop
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=1
      - MYSQL_DATABASE=tzomet_sfarim
      - MYSQL_TCP_PORT=3306
    ports:
      - "3306:3306"
    build: ./database
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "127.0.0.1" ]
      interval: 30s
      timeout: 30s
      retries: 5
      start_period: 60s

  backend:
    container_name: tzomet-sfarim-shop-backend
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=compose
    build: ./backend
    depends_on:
      database:
        condition: service_healthy

  frontend:
    container_name: tzomet-sfarim-shop-frontend
    ports:
      - 5173:80
    build: ./frontend
